class BookingStatus():
    # BOOKING_PENDING = 0
    BOOKING_CONFIRMED = 0
    USER_ATTENDED = 1
    BOOKING_CANCELED = 2


class EventLocation():
    EVENT_OFFLINE = 0
    EVENT_ONLINE = 1

class EventStatus():
    EVENT_PENDING=0
    EVENT_AVAILABLE = 1
    EVENT_FULL = 2
    EVENT_COMPLETED = 3
    EVENT_CANCELED = 4
    EVENT_APPLY_END = 5