"""Upgraded all schema

Revision ID: 123f2281991d
Revises: 84cfaea00a5e
Create Date: 2025-05-06 14:56:32.647788

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '123f2281991d'
down_revision = '84cfaea00a5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('bookings_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('bookings_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'qrcode', ['qrcode_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('code')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_start_date', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('event_end_date', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('apply_start_date', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('apply_end_date', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('curr_attendees', sa.Integer(), nullable=False))
        batch_op.drop_constraint('events_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'image', ['img_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('price')
        batch_op.drop_column('event_date')
        batch_op.drop_column('current_attendees')
        batch_op.drop_column('event_start_time')
        batch_op.drop_column('event_end_time')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_end_time', mysql.TIME(), nullable=False))
        batch_op.add_column(sa.Column('event_start_time', mysql.TIME(), nullable=False))
        batch_op.add_column(sa.Column('current_attendees', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('event_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('events_ibfk_3', 'image', ['img_id'], ['id'])
        batch_op.drop_column('curr_attendees')
        batch_op.drop_column('apply_end_date')
        batch_op.drop_column('apply_start_date')
        batch_op.drop_column('event_end_date')
        batch_op.drop_column('event_start_date')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', mysql.VARCHAR(length=255), nullable=False))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bookings_ibfk_2', 'qrcode', ['qrcode_id'], ['id'])
        batch_op.create_foreign_key('bookings_ibfk_1', 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###
