"""remove is_valid in qrcode schema

Revision ID: 2beeefc6620a
Revises: 8d5d4a03f733
Create Date: 2025-05-06 15:17:04.426394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2beeefc6620a'
down_revision = '8d5d4a03f733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrcode', schema=None) as batch_op:
        batch_op.drop_column('is_valid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('qrcode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_valid', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
