"""add is_admin_main to user schema

Revision ID: 8c877ffe5ead
Revises: 2beeefc6620a
Create Date: 2025-05-07 11:51:31.736459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c877ffe5ead'
down_revision = '2beeefc6620a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin_main', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin_main')

    # ### end Alembic commands ###
